### ISSUE TITLE
Idea - Streaming URLs & Format Conversions

### ISSUE THREAD

**Issue by nodecentral** [netsmarttech/node-red-contrib-ui-media#7]
Provide support for streaming urls and optional ffmpeg integration,  so with ffmpeg installed you can choose your stream url and type  (e.g mpeg.ts)  and have the node  transmux it into something else etc.

**Comment by gfcittolin** [comment]
Hi,
Thanks for the suggestion. I fear I haven't got the full picture of your need, what exactly would be your use case? I ask, because the node already supports setting any user-defined URL by setting `msg.src` to the desired one. There are already ffmpeg nodes for Node-RED, so maybe you could already do what you're suggesting.

**Comment by gfcittolin** [comment]
I'm closing this for now due to lack of activity and (at least partial) support for the required functionality with a combination of this and other node-red nodes
